#!/usr/bin/env bash
# buzz fizz
var=1
while [ "$var" -le 100 ]
do
	fizz=$((var%3))
	buzz=$((var%5))
	if [ $fizz = 0 ] && [ $buzz = 0 ]
	then
		echo "FizzBuzz"
	elif [ $fizz = 0 ]
	then
		echo "Fizz"
	elif [ $buzz = 0 ]
	then
		echo "Buzz"
	else
		echo "$var"
	fi
	((var++))
done
