#!/usr/bin/env bash
# File or not to file
var=school
if [ -e $var ]; then
	echo "school file exists"
		if [ -s $var ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
			if [ -f $var ]; then
				echo "school is a regular file"
			fi
else
	echo "school file does not exist"
fi
	
